### ISSUE TITLE
:focus bar outside tree-view when tree-view is not leftmost

### ISSUE THREAD

**Issue by ssorallen** [atom/one-dark-ui#104]
If you install tool-bar and tool-bar-main and position the toolbar on the left, you can recreate the problem that using `position: fixed` causes: the `:focus` bar sits outside the tree view's container. Switching to `position: absolute` fixes this.

Blue focus bar is outside the tree view container:

<img width="253" alt="screen shot 2015-11-04 at 10 18 52 am" src="https://cloud.githubusercontent.com/assets/29612/10947644/f63cf5d0-82dd-11e5-88d6-b2da7de87916.png">

(Same issue as https://github.com/atom/one-light-ui/issues/41)

**Comment by simurai** [comment]
Hmm.. this is quite tricky..

- `position: absolute` doesn't work when the tree-view is scrolled up. Because the `:before` also scrolls up and you can't see it anymore.
- The blue marker could be added to `.tree-view-resizer` so it doesn't scroll and stays at the top, but for some reason the `:focus` doesn't work anymore.. probably intended to only make it work on `.tree-view`.

**Comment by ssorallen** [comment]
@simurai I might have a solution to this. Remove the `left: 0;` from `:before` so the bar uses its natural left position. Use `margin-left: -@component-icon-padding;` to pull it to the left edge of the tree-view's container. The tree-view uses `padding-left: @component-icon-padding;`. All together:

```less
.tree-view::before {
  content: "";
  position: fixed;
  pointer-events: none;
  z-index: 1;
  top: @ui-padding-pane;
  margin-left: -@component-icon-padding;
  height: @ui-tab-height;
  bottom: 0;
  width: 2px;
  background: @base-accent-color;
  opacity: 0;
  transform: scaleY(0);
  transition: opacity .16s, transform .16s cubic-bezier(.80, 0, .90, .53);
}
```
