### ISSUE TITLE
Compact tabs with Compact Layout Mode?

### ISSUE THREAD

**Issue by Haraldson** [atom/one-dark-ui#120]
Personally not a fan of big, wide tabs (when the number of tabs allow for it) with centered labels and massive amounts of space around.

How about having the file tabs use only the space they need when Layout Mode is set to Compact? Alternatively offer this as a separate setting?

(Another setting I’d like to see, but that I don’t feel like deserves an entire ticket of its own, is the ability to disable that colored highlight on tabs and Tree View.)

**Comment by simurai** [comment]
> How about having the file tabs use only the space they need when Layout Mode is set to Compact? Alternatively offer this as a separate setting?

Could be its own setting, but to couple it with the "Compact Mode" might make sense. I'll give that a try. Similar to #94

> (Another setting I’d like to see, but that I don’t feel like deserves an entire ticket of its own, is the ability to disable that colored highlight on tabs and Tree View.)

What's the reason you would like to disable the colored highlight? You could remove it in your `styles.less` with:

```less
// Remove focus marker
.theme-one-dark-ui,
.theme-one-light-ui {
  .tree-view::before,
  .tab::before {
    display: none;
  }
}
```

**Comment by Haraldson** [comment]
Happy to read your positive reply! Regarding the color highlighting, I just have no need for it I guess.

I hacked my `styles.less`. yesterday, to reflect the wishes I described above. It probably needs to be cleaned up though, but the concept’s there;

```less
.tab-bar {
    -webkit-box-align: start;

    .tab,
    .tab.active {
        flex: 0 0 auto;
        min-width: auto;

        &:before { display: none; }

        .title {
            padding-right: 24px;
            text-align: left;
        }
    }

    // Also desaturate file icon for inactive tabs
    .tab:not(.active) .title:before { color: rgba(255, 255, 255, .25); }
}

// Feels like the tabs are jammed too tightly against the editor’s first
// line of code below. Adding padding-top to the editor gives me the
// correct background color, but I’m sure there’s a better way
atom-pane-container atom-pane .item-views > * { padding-top: 12px; }
```

**Comment by simurai** [comment]
> // Feels like the tabs are jammed too tightly against the editor’s first
    // line of code below. Adding padding-top to the editor gives me the
    // correct background color, but I’m sure there’s a better way
    atom-pane-container atom-pane .item-views > * { padding-top: 12px; }

Bugs me too a bit. Maybe

```less
atom-text-editor:not(.mini)::shadow {
  .scroll-view,
  .gutter {
    padding-top: 12px;
  }
}
```

then code doesn't get cut off before reaching the top.

![screen shot 2016-02-12 at 6 44 16 pm](https://cloud.githubusercontent.com/assets/378023/13003393/a7665fb2-d1b8-11e5-8802-2b6f1869cd1f.png)
