### ISSUE TITLE
Find and replace bar

### ISSUE THREAD

**Issue by badri-n18** [atom/one-dark-ui#150]
Pls make the border of the "Find" bar turn red, when no results are found, so that it can provide a quick visual info. to the user

**Comment by simurai** [comment]
@badri-n18 Do you mean like this:

![find](https://cloud.githubusercontent.com/assets/378023/16872521/3a3ddce2-4ac8-11e6-880e-3704026aed3c.gif)

First the `find-and-replace` package would need to provide a class. Something like `has-result` and `has-no-result`.  Then themes could use to style it in different ways. Might be nice to add it. 👍

**Comment by badri-n18** [comment]
yes, exactly

**Comment by simurai** [comment]
Ok, so far this is blocked by https://github.com/atom/find-and-replace/issues/761

**Comment by simurai** [comment]
There is now a PR to unblock this: https://github.com/atom/find-and-replace/pull/798

**Comment by simurai** [comment]
Ok, this is a bit tricky if the syntax theme uses either a green-ish or red-ish background. Because this theme uses that as accent color. So in the example below it looks like there is a match (green):

![screen shot 2016-10-29 at 4 13 34 pm](https://cloud.githubusercontent.com/assets/378023/19827903/ca248716-9df2-11e6-9e41-11220c015ffe.png)

**Comment by simurai** [comment]
Starting with Atom `1.13 Beta`, here something to test in your `styles.less` file:

```less
@import "ui-variables";

// Colorize find-and-replace based on results
.find-and-replace {
  &.has-no-results .find-container atom-text-editor[mini].is-focused {
    border-color: @text-color-error;
    box-shadow: 0 0 0 1px @text-color-error;
    background-color: mix(@text-color-error, @input-background-color, 10%);
    .selection .region {
      background-color: mix(@text-color-error, @input-background-color, 50%);
    }
    .cursor {
      border-color: @text-color-error;
    }
  }

  &.has-results .find-container atom-text-editor[mini].is-focused {
    border-color: @text-color-success;
    box-shadow: 0 0 0 1px @text-color-success;
    background-color: mix(@text-color-success, @input-background-color, 10%);
    .selection .region {
      background-color: mix(@text-color-success, @input-background-color, 50%);
    }
    .cursor {
      border-color: @text-color-success;
    }
  }

  &.has-results    .find-container .result-counter { color: @text-color-success; }
  &.has-no-results .find-container .result-counter { color: @text-color-error; }
}
```
