### ISSUE TITLE
Use if/else instead of contrast()

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-ui#16]
... to detect if a Syntax theme is light or dark.

@braver Ohh.. snap! [That's](https://github.com/braver/isotope-ui/blob/master/styles/ui-variables.less#L37-L43) how you do `if/else` in Less. I think I tried something like

```less
& when (luma(@syntax-background-color) < 50%) {
  @base-background-color: @syntax-background-color;
}
& when (luma(@syntax-background-color) >= 50%) {
  @base-background-color: #333;
}
```

but didn't seem to work with variables. Then (mis)used the `contrast()` function instead.

btw. I also like the foreground/background naming and the modular scales. Saw [modularscale.com](http://www.modularscale.com/) the other day which is a nice tool.

**Comment by simurai** [comment]
__Note to self__: This should work

```less
@ui-a:       hsl(252, 11%, 18%); // fallback
@ui-a:       @syntax-background-color;
@ui-a-h:     hue(@ui-a);
@ui-a-s:     min( saturation(@ui-a), 12%);

@ui-a-color: @ui-a;
.ui-a-color() when (luma(@syntax-background-color) > 50%) {
  @ui-a-color: hsl(@ui-a-h, @ui-a-s, 24%);
}
.ui-a-color();
```
