### ISSUE TITLE
Improve buttons layout in notifications

### ISSUE THREAD

**Issue by abe33** [atom/one-dark-ui#193]
Currently, when creating a notification with many buttons that force them to be wrapped at the end of the line, it looks like this: 

<img width="476" alt="ready_js_ ___github_kite" src="https://cloud.githubusercontent.com/assets/247140/22105141/01cae526-de43-11e6-8484-decadd4d6b14.png">

Playing around with the CSS the rules below would enable to get the following render:

<img width="485" alt="ready_js_ ___github_kite" src="https://cloud.githubusercontent.com/assets/247140/22105387/00d76cb0-de44-11e6-9ef0-2f0887d19f31.png">

```css
atom-notification .btn-toolbar {
  margin-top: 10px;
  margin-bottom: -5px;
}

atom-notification .btn-toolbar > .btn{
  margin-left: 0;
  margin-bottom: 5px;
}
```

Of course, when there's only one button or when the buttons all fit on one line it still render as expected: 

<img width="484" alt="ready_js_ ___github_kite" src="https://cloud.githubusercontent.com/assets/247140/22105431/368aa958-de44-11e6-91cd-74ad4bbf91f4.png">

Sample code used in the test:

```js
atom.notifications.addInfo('This is an info notification', {
  description: 'With some description', 
  dismissable: true, 
  buttons: [
    {text: 'Button with very long text'}, 
    {text: 'Another button with very long text'}, 
    {text: 'Button'}
  ]
})```
