### ISSUE TITLE
Tab height shrank with upgrade, and the layout mode option is gone

### ISSUE THREAD

**Issue by mvassilevsky** [atom/one-dark-ui#198]
Upon upgrading to 1.10.1, my tabs are significantly smaller, and I don't see the option to revert that change.

Downgrading to 1.9.2 for comparison, it's as if the Compact layout mode were being forced.

**Comment by simurai** [comment]
Yes, the "Spacious" mode got removed in https://github.com/atom/one-dark-ui/pull/197.

In Atom `1.17` there will be [docks](https://github.com/atom/atom/pull/13977) on the side and bottom that have tabs. Since the docks are typically more narrow and have less space, the tabs in this theme got changed to be smaller and more compact. We were considering having different tabs for the center and the docks, but that didn't look right and felt inconsistent.

There are forks like https://atom.io/themes/pristine-ui, but not sure if they will keep the tabs the same.

It's also possible to restyle the tabs in your `styles.less` file. Here just a quick start, but would need some more styling to get closer to the "Spacious" mode version:

```less
// One themes with spacious tabs
.theme-one-dark-ui,
.theme-one-light-ui {

  @import "ui-variables";

  .tab-bar {
    padding-top: @component-padding;
    box-sizing: content-box;
    .tab {
      border-top: 1px solid transparent;
    }
    .tab.active {
      border-top-color: @base-border-color;
    }
  }
}
```

![screen shot 2017-04-12 at 7 41 19 pm](https://cloud.githubusercontent.com/assets/378023/24953910/1da846c4-1fb8-11e7-9bc0-31ecc76b336e.png)

**Comment by mvassilevsky** [comment]
That's unfortunate. Looks like I'll be sticking with 1.9.2, then.

**Comment by simurai** [comment]
> That's unfortunate. Looks like I'll be sticking with 1.9.2, then.

Hopefully `1.9.2` will last for a while without issues. 🙏 

I also liked the spacious tabs, but after using the new docks for a while, having compact tabs made a lot more sense. Once Atom `1.17` is out (next month) or now already in [Beta](https://atom.io/beta), I would encourage to try it out too.

Closing as `wontfix`.

**Comment by havthgem** [comment]
I'm very sad 😭, because I like "Spacious" layout mode very much!
It was very sorrowful to remove the good feature after adding a new feature.
But, Hope "One dark" better.

**Comment by simurai** [comment]
@havthgem Yeah, I hear ya. :worried:

It's just that the "spacious" tabs felt like taking up too much space once used in the new docks. Only two things to offer is using a fork or try to restyle this theme, see ☝️ comment https://github.com/atom/one-dark-ui/issues/198#issuecomment-293540115 for more details.

**Comment by havthgem** [comment]
I saw, I have started trying to adapt to the new layout 😂.

**Comment by tillkruss** [comment]
@simurai: The small tabs are fine on a laptop, but on a 5k display I can hardly see them.

**Comment by ErrOrnAmE** [comment]
Maybe this update could have waited the release of 1.17.
In the meantime, lot of users will have a negative feeling about this change

**Comment by utkarshkukreti** [comment]
@tillkruss I've been using the following to increase the white space since I upgraded to Atom 1.17 today (which included this update I believe):

```less
.theme-one-dark-ui {
  .tab-bar {
    height: 3em;
    .tab {
      line-height: 3em;
      .close-icon {
        top: 0.75em;
      }
    }
  }
}
```

It doesn't look as good as the old version to me, but it's much better than the new one on my 27" 4K display.
