### ISSUE TITLE
New tab animation like Safari

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/one-dark-ui#203]
It will be awesome if this ui can add `new tab animation` like Safari.

![new-tab-animation](https://cloud.githubusercontent.com/assets/20783502/24997778/688df08c-206a-11e7-8af4-8314ae2e4c8f.gif)

**Comment by simurai** [comment]
Here a quick try:

```less
.tab-bar .tab {
  animation: tabs-animation 0.2s ease-out;
}

@keyframes tabs-animation {
  0% { flex: 0; }
}
```

![tabs](https://cloud.githubusercontent.com/assets/378023/25116618/dc012ec6-2448-11e7-8a76-5787b093c1c1.gif)

An issue is that when closing a tab, the other tabs don't know about it and don't animate. That's something the tabs package would have to add.
