### ISSUE TITLE
Bracket Matcher Highlight color

### ISSUE THREAD

**Issue by svipben** [atom/one-dark-ui#236]
Currently color for **Highlight Matching Line Number** in `bracket-matcher` is too dark and I can't even see line number through it... So my suggestion is to change it or reduce darkness.

![image](https://user-images.githubusercontent.com/10441177/35334490-434734fe-011b-11e8-981e-2d0fe8d8dfd9.png)

Atom: 1.23.3
OS: macOS

**Comment by simurai** [comment]
@svipben What's the **Syntax** theme you're using?

This should be fixed with https://github.com/atom/bracket-matcher/commit/395d2e0e373b79ba0618f427fe479aef9b69fe08. I think part of Atom `1.25`.

In the meantime, you can manually add this to your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Fix bracket-matcher gutter, should land in Atom 1.25
@import "syntax-variables";
.line-number.bracket-matcher.bracket-matcher {
  color: @syntax-gutter-text-color-selected;
  background-color: @syntax-gutter-background-color-selected;
}
```
