### ISSUE TITLE
Highlight color in search field wrong

### ISSUE THREAD

**Issue by dtmuller** [atom/one-dark-ui#237]
### Description

The highlight color in the search field is same as text color and makes it unreadable. Change highlight color or invert highlighted text.

![screenshot from 2018-02-07 10-32-05](https://user-images.githubusercontent.com/594608/35909191-118acf10-0bf3-11e8-865b-019db0a3e6a7.png)

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

one-dark-ui: 1.10.8

OS: Linux

**Comment by simurai** [comment]
Anyone can reproduce this? Seems Linux specific.

Here something to paste in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file to see if that changes anything.

```less
atom-text-editor[mini] .selection .region,
atom-text-editor[mini].is-focused .selection .region {
  background-color: red;
}
```

Selection in search fields should now be **red**.

![image](https://user-images.githubusercontent.com/378023/35952434-418741fa-0cc3-11e8-91f1-aa9517503023.png)

/cc @ungb
