### ISSUE TITLE
Allow/Set contrast on the thumb of the scroll bar...

### ISSUE THREAD

**Issue by artisancreek** [atom/one-dark-ui#241]
It would be helpful if the scroll bar thumb would have more contrast in the theme because it is difficult for some to see the thumb - especially in large files (it is small). 

Either allow configuration of the contrast (or lighter) or set it to stand out a bit more so that it can be easily found and selected.

**Comment by simurai** [comment]
@artisancreek Mind posting a screenshot? The scrollbar depends on which OS and setting you are using.

**Comment by artisancreek** [comment]
<img width="584" alt="screen shot 2018-03-09 at 5 52 10 pm" src="https://user-images.githubusercontent.com/4069583/37235370-b0987638-23c3-11e8-8543-f84d07832204.png">
<img width="580" alt="screen shot 2018-03-09 at 5 53 05 pm" src="https://user-images.githubusercontent.com/4069583/37235371-b0b1e4a6-23c3-11e8-8230-8918d02808e4.png">



Here are two screen shots. One showing the tiny thumb and one larger. For me, the contrast isn't enough to where I can find that thumb for dragging purposes easily. 
This is on a Mac Book Pro (Retina, 15-inch, Mid 2015; macOS Sierra (10.12.6); Graphics: AMD Radeon R9 M370X 2048 MB; Intel Iris Pro 1536 MB

I hope that helps...

**Comment by simurai** [comment]
I see. Yeah, agreed, a little more contrast would help. 👍

**Comment by simurai** [comment]
There is now a PR #247, but it will take till Atom 1.27 until it changes. If you can't wait, you could change it yourself by adding the following to your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// style scrollbar thumb
@import "syntax-variables";

.scrollbars-visible-always,
.scrollbars-visible-always atom-text-editor {
  ::-webkit-scrollbar-thumb {
    background: lighten(@syntax-background-color, 16%);
  }
}
```
