### ISSUE TITLE
Sticky projects headers make clicking the item above a selected folder impossible

### ISSUE THREAD

**Issue by Ben3eeE** [atom/one-dark-ui#257]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When selecting a folder in the tree-view it's not possible to click on the file above it.

![one dark sticky header](https://user-images.githubusercontent.com/1058982/39306612-ee49f43a-4960-11e8-9601-0f904d55ee05.gif)

### Steps to Reproduce

1. Open Atom in safe mode `.\atom --safe` in the `atom/atom` repository
2. Ensure you have the `one-dark-ui` `Make tree-view project headers sticky` setting enabled
3. Select the `docs` folder
4. Try to Expand the `benchmarks` folder that is above

**Expected behavior:** Expanding the `benchmarks` folder

**Actual behavior:** Collapses the `docs` folder

**Reproduces how often:** 100%

### Versions

Atom    : 1.28.0-dev-59cb1dd50
one-dark-ui@1.12.2

### Additional Information

![image](https://user-images.githubusercontent.com/1058982/39306809-6d90a6c6-4961-11e8-8aa5-d004076d8f2e.png)

![image](https://user-images.githubusercontent.com/1058982/39306831-76d13e80-4961-11e8-9776-422c5936defe.png)

I also have some custom styles for the tree-view in my personal stylesheet but disabling them did not resolve the issue.

```less
// Style tree-view open folder indent guides
.tree-view .selected:before {
 background: hsla(0,0%,100%,.1); // show lines underneath
}

.tree-view .directory {
 & > .list-item:before {
   visibility: hidden; // hide arrows
 }
 .selected > .header.list-item ~ .entries.list-tree {
   background: linear-gradient(to right, transparent 24px, lighten(@base-background-color, 10%) 24px, lighten(@base-background-color, 10%) 25px, transparent 25px);
 }
 .header.list-item:hover ~ .entries.list-tree {
   background: linear-gradient(to right, transparent 24px, @text-color-subtle 24px, @text-color-subtle 25px, transparent 25px);
 }
}
```
