### ISSUE TITLE
Customizing font size

### ISSUE THREAD

**Issue by vegar** [atom/one-dark-ui#28]
The [read.me](https://github.com/atom/one-dark-ui#customize) states that we can override the textsize used for the UI with the following code:

```css
.theme-one-dark-ui {
    font-size: 14px;
}
```

but that doesn't work for me.

It also states that we can change the text size in the tabs by the following code:

```css
.theme-one-dark-ui {
  .tab-bar {
      font-size: 14px;
   }
}
```

but that doesn't work either. 

To change the text size, I need to use the following code:

```css

.theme-one-dark-ui {
  .tab-bar {     
      .tab {
          font-size: 14px;
      }
  }
  .tree-view { font-size: 14px; }
  .status-bar { font-size: 12px; }
}
```

If I use the `!important` directive, the first example does in fact change all areas, but it also gives a less compilation error, so I guess that's not the right solution..
