### ISSUE TITLE
Scrollbars are extremly big in latest version.

### ISSUE THREAD

**Issue by philipgiuliani** [atom/one-dark-ui#32]
The new update of the theme looks good, i like it, but i also liked the flat-style ui.

Its just an opinion, but aren't the scrollbars extremly large now? They are a way thicker than the default OSX Scrollbars.

![bildschirmfoto 2015-04-07 um 08 40 51](https://cloud.githubusercontent.com/assets/5446019/7018208/d511a1e4-dd01-11e4-8f49-25748a794db6.png)

Revert:
```less
.scrollbars-visible-always /deep/ ::-webkit-scrollbar {
  width: 1em;
  height: 1em;
}
```
