### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by simurai** [atom/one-dark-ui#40]
Would remove extra padding. Like it was pre `0.6.0`.

Either:

- could be changed in the settings.
- or automatically based on window size (media queries).

**Comment by yaroshevych** [comment]
+1 for this. There is an extra padding on the right and on the top of window.
![untitled_-__users_oleg_projects_healthems-newarchitecture_-_atom_and_1____start_sh__java_](https://cloud.githubusercontent.com/assets/564246/7044097/6b756372-ddf8-11e4-89f8-5d313492b103.png)

**Comment by dcalhoun** [comment]
I'd vote for a settings config.

**Comment by danqing** [comment]
+1! I think the old look is great.

**Comment by iclanzan** [comment]
I would also like to be able to reclaim that space back please.

**Comment by mark-** [comment]
+1 The main reasons I switched to this theme was that it had much less padding and chrome than the old default theme.

**Comment by bradpurchase** [comment]
+1 I strongly dislike the new padding. Switched back to "Atom Dark" which I generally do not prefer over this theme.

**Comment by jsg2021** [comment]
+1
I'll trim it with the user style sheet for now 😊

**Comment by bradpurchase** [comment]
@jsg2021 I wonder if you would be able to upload it is a "one-dark-mini" package or something?

**Comment by jsg2021** [comment]
`Atom` Menu > `Open Your Stylesheet`

```less
atom-workspace.theme-one-dark-ui {
    @pad: 2px;
    padding-right: @pad;
    atom-panel-container.left:empty {padding-left: @pad;}
    atom-pane-container atom-pane {padding-top: @pad;}
}
```

change pad to 0 if you want no padding.

**Comment by danqing** [comment]
We just need something like that wrapped in a settings item

**Comment by mark-** [comment]
Can the compact mode also remove the rounded corners on the tabs?

**Comment by brendanfalkowski** [comment]
I would revert also. On a MacBook Air that extra 3mm of padding is just a waste. I switched from Sublime to Atom *because* this theme was so compact.

**Comment by lloeki** [comment]
I concur, the old version was so much better I actually wondered if I hit a bug or something. It's now even worse than the `Atom` theme.

**Comment by lloeki** [comment]
@jsg, this is insufficient: missing light theme, rounded corners and angled slab are still there, as is the silly nerve-wracking, attention-grabbing tab focus animation. This theme used to be a paramount example of unobtrusive, clean minimalism done right. Now it demonstrates just how much St-Exupery was right.

> It seems that perfection is attained not when there is nothing more to add, but when there is nothing more to remove.

**Comment by lloeki** [comment]
Here goes:

```less
atom-workspace {
  &.theme-one-dark-ui,
  &.theme-one-light-ui {
    @pad: 0px;
    padding-right: @pad;
    atom-panel-container.left:empty { padding-left: @pad; }
    atom-pane-container atom-pane   { padding-top:  @pad; }

    .tab-bar {
      li.tab .title { border-top: 0px; }
      li.tab::after,
      li.tab::before {
        transition: none;
        border-radius: 0;
      }
      li.tab::before {
        margin-top:    -1px;
        margin-bottom: -1px;
        height: 32px + 2px;
        width: 3px;
      }
      li.tab::after {
        margin-bottom: -1px;
        height: 32px + 1px;
        border-right: 0px;
        border-top:   0px;
      }
      .close-icon { transition: none; }
    }

    .item-views {
      border-radius: 0;
      border-left:  0;
      border-right: 0;
    }
  }
}
```

Note that I like the active tab slab to be chunkier.

**Comment by jsg2021** [comment]
Thats what the user stylesheet is for! :) One theme cannot satisfy everyone.

I actually have enjoyed most of the changes except the extra padding. (and my syntax theme hits a weird case so my UI is a darker color)  @lloeki you mentioned the tab animation... I've actually caught myself just switching tabs to watch it :)

**Comment by benogle** [comment]
I just want to say that I like the new padding. And the animation in some form has been there since the beginning of this theme. 

> Thats what the user stylesheet is for!

Agree with this!

**Comment by rockymadden** [comment]
Thanks, @lloeki!

**Comment by brendanfalkowski** [comment]
Since this is the default theme (and my preferred theme too) I'd want the basis to serve the widest set of users: small, middle, and big screens. Since the padding really does subtract coding space from small screen users without adding usability (particularly the right edge) doesn't it make sense to favor a less padded default?

I get the user stylesheet capability, but I'm not *trying* to hack every component of Atom. I mostly just want a good editor that works. Any user-changes introduced are another thing to maintain that's not my actual job. I feel like hack-ability is a pro of Atom, not a mandate.

**Comment by mnquintana** [comment]
@brendanfalkowski I think it would be worth at least exploring a lower padding value in the editor frame, but not getting rid of it entirely. That's up to @simurai though.

**Comment by brendanfalkowski** [comment]
Noticed the search UI is super-padded now too.

![screen shot 2015-04-14 at 2 43 39 pm](https://cloud.githubusercontent.com/assets/214924/7144615/b7131ef8-e2b4-11e4-93ee-13d3e499efeb.png)

I'm guessing this is a LESS var that's used liberally for all padding? Probably shouldn't always be the same value, I'm spotting more and more cases like this: https://github.com/atom/one-dark-ui/issues/51

**Comment by yaroshevych** [comment]
Guys, do you know how to downgrade this theme? Maybe some sort of ```npm``` command?

**Comment by lloeki** [comment]
Clone the repo in `~/.atom/pacakges` and checkout a previous version.

**Comment by philipgiuliani** [comment]
@yaroshevych @brendanfalkowski with in the last atom version (released 13 hours ago) the padding is now much smaller..

**Comment by simurai** [comment]
Yes, Find+Replace and command palette got fixed in Atom `0.191.0`.

The editor padding (frame) is still there though. So adding a compact mode is still under consideration.

**Comment by brendanfalkowski** [comment]
The `0.191.0` fixes look good. If it were me, for the editor frame's padding: top = ~1/2 the current gap, and right = 0. With the mini-map plugin (I figure most people us it) that padding-right doesn't buffer between the code frame and window — it's just space. Doesn't kill me as-is though (theme is great).

**Comment by jsg2021** [comment]
>  With the mini-map plugin (I figure most people us it)

that's probably an over generalization.

**Comment by simurai** [comment]
There is now a `sm-compact-mode` branch. It automatically switches between the modes based on the window size.

small screen (13" or lower): `11px` font size + removes the "frame"
![compact-mode-1](https://cloud.githubusercontent.com/assets/378023/7275098/e1cc4b72-e93c-11e4-9c75-35364ce4ba5c.png)

medium screen: `12px` font size
![compact-mode-2](https://cloud.githubusercontent.com/assets/378023/7275101/e66d557c-e93c-11e4-8ef2-fb220595f810.png)

large screen ( larger than 1690w or 950h ):  `14px` font size
![compact-mode-3](https://cloud.githubusercontent.com/assets/378023/7275106/eb070a88-e93c-11e4-84e1-97514a7cb0b6.png)

There could be a setting to lock one of the modes so it would stay, no matter what size the window is?

**Comment by jsg2021** [comment]
I like that :) :+1:

**Comment by philipgiuliani** [comment]
Really cool, i would preffer a setting instead of using the window size.

**Comment by danqing** [comment]
A setting will be great!!

**Comment by mark-** [comment]
Great work! +1 for a setting

**Comment by brendanfalkowski** [comment]
I'd prefer individual settings over "preset bundles", even though making it responsive is a cool idea.

I wouldn't want the tree text getting super small because my screen was (still need to read it). I'd just toggle the tree on/off when I need more space. I do that already when working from laptop.

Wouldn't want the padding getting thicker because I'm on a big screen. The chrome is not the content — if I'm docked up I want that big screen for content.

**Comment by simurai** [comment]
Ok, added a setting:

![screen shot 2015-04-29 at 1 30 21 pm](https://cloud.githubusercontent.com/assets/378023/7384931/07ac2b8e-ee77-11e4-94b2-02f64775b07f.png)

and made a PR. #58

> @brendanfalkowski I'd prefer individual settings over "preset bundles"

The `auto` mode is a "preset bundle". Changes padding combined with font size. But you can lock the layout to either `compact` or `spacious` and also change the font size to whatever you like.

**Comment by jsg2021** [comment]
:+1: nice!

**Comment by brendanfalkowski** [comment]
Looks like a good start, will play with once it hits the updates.

**Comment by lodev09** [comment]
for those of you having problems scrolling the vertical scroll bar because of the padding/border (i.e. hard to catch the scroll bar with the mouse if you point the cursor to the edge of the window), here is the quick fix:

```less
atom-workspace {
    &.theme-one-dark-ui,
    &.theme-one-light-ui {
        @zero: 0px;
        atom-pane-container atom-pane {
            padding-right:  @zero;
            .item-views { border-right: @zero; }
        }
    }
}
```
I'm on Windows 10
