### ISSUE TITLE
The "Find file" prompt has spacing issues

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/one-dark-ui#51]
Hitting `CMD + P` to raise the file prompt, noticed there's a bigger gap between file name and path since the recent updates:

![screen shot 2015-04-14 at 2 00 08 pm](https://cloud.githubusercontent.com/assets/214924/7143686/c2c6b8a0-e2ae-11e4-96fb-33265ac29a3b.png)

Related: not sure if this overlay is narrower now too, but (in Magento) paths are super deep and redundant (lots of theme inheritance). It's often hard to select the correct file because the path overflows the window. Could this overlay be wider by 200px or relative to the content?

**Comment by simurai** [comment]
The spacing got fixed part of #41 and should already be in Atom `0.191.0`.

Changing the width based on the content sounds good. Maybe annoying if it changes while you type, but if it could keep the initial width.

**Comment by simurai** [comment]
Or not truncate and let it wrap on multiple lines?

![screen shot 2015-04-15 at 5 57 48 pm](https://cloud.githubusercontent.com/assets/378023/7155399/6843ea38-e399-11e4-9b2f-06f4a05e891e.png)

**Comment by mnquintana** [comment]
> Changing the width based on the content sounds good. Maybe annoying if it changes while you type, but **if it could keep the initial width.**
:+1: Sounds good to me – truncating long file paths can be somewhat annoying.

> Or not truncate and let it wrap on multiple lines?
Hmmm maybe... how would that look with multiple entries (some of which don't wrap to multiple lines)?

**Comment by simurai** [comment]
![screen shot 2015-04-15 at 9 18 40 pm](https://cloud.githubusercontent.com/assets/378023/7158449/2746a77a-e3b5-11e4-9366-097f2b52829e.png)

**Comment by brendanfalkowski** [comment]
Great work! Wider + wrapping looks nice. Not at all worried about the mix of wrapped/unwrapped lines, so much better to see the full path.

**Comment by mnquintana** [comment]
Yup, looks :+1: to me too

**Comment by simurai** [comment]
Two things that came to mind:

1. Should this be the default for all themes? In that case it should be changed in Core.
2. Does the file name need to be repeated in the full path? Could also be just:

```
file.txt
path/to/file/
```

Then sometimes 2 lines wouldn't be needed and it might even be easier to read the path?

**Comment by brendanfalkowski** [comment]
I always need to see the filename + path because of this scenario (Magento file system):

```
/app/design/frontend/base/default/template/catalog/product/view.phtml
/app/design/frontend/base/default/template/catalog/product/list/view.phtml
/app/design/frontend/enterprise/default/template/catalog/product/view.phtml
/app/design/frontend/enterprise/default/template/catalog/product/list/view.phtml
/app/design/frontend/custom/default/template/catalog/product/view.phtml
/app/design/frontend/custom/default/template/catalog/product/list/view.phtml
```

When I fuzzy search, I always type like this:

`custcatprodviewphtml`

That gets me down to two files (the are tons of exact match filenames between modules) so finding the right one needs to be pretty specific.

If the path + filename are separated it's harder to compare them in a list, and if one was absent then I couldn't identify the right file.

**Comment by simurai** [comment]
I'm gonna close this in favor of https://github.com/atom/fuzzy-finder/issues/17 since truncating long paths is not just an issue with this theme, but affects all themes.

As a quick fix, this should make the lines wrap:

```less
.fuzzy-finder {
  &.select-list ol.list-group li .primary-line,
  &.select-list ol.list-group li .secondary-line {

    // let lines wrap
    text-overflow: initial;
    white-space: initial;
    overflow: initial;

    // reduce line-height
    line-height: 1.4em;
    padding-top: .2em;
    padding-bottom: .2em;

    // make sure wrapped lines get padding
    padding-left: 21px;
    &.icon:before {
      margin-left: -21px;
    }
  }
}
```
