### ISSUE TITLE
Tab contents rendered without subpixel anti-aliasing

### ISSUE THREAD

**Issue by wiox** [atom/one-dark-ui#82]
![](http://i.imgur.com/dL40dSY.png)
![](http://i.imgur.com/fZonTgr.png)
_(zoom to see the beautiful subpixel anti-aliasing in effect.. or lack of)_

A little testing has bought me to conclude that the following CSS rule is the culprit:
```css
.tab-bar .tab .title {
    -webkit-mask: linear-gradient(to left, rgba(0, 0, 0, 0), #000000 1em) no-repeat;
}
```

This is used for the fading effects when filenames overflow out of the tab. I have resorted to removing this rule from my own Atom client.

Hopefully a solution can be found that allows for the fancy effect to remain whilst improving the rendering.

Operating System: Windows 8.1
Atom Version: 1.0.0
One Dark UI Version: 0.9.1
