### ISSUE TITLE
Support OSX Style Tabs (Close on the left)

### ISSUE THREAD

**Issue by zenopopovici** [atom/one-dark-ui#93]
I think it should be an option.

```less
.tab-bar .tab .close-icon {
    left: 0;
    right: auto;
}
.tab-bar .tab:hover .title {
    -webkit-mask: linear-gradient(to right, rgba(0, 0, 0, 0), #000000 1em) no-repeat;
    -webkit-mask-position: 1em 0;

    &::before { content: ' '; }
}
```
